### ISSUE TITLE
Different Globalization Options

### ISSUE THREAD

**Issue by DarthMaul113** [scintilla0/jquery.maxlength#1]
@scintilla0 Is there any way to change the globalization option so the formatting matches the one i'm using in my app?

**Comment by scintilla0** [comment]
Currently no, but you can elaborate on it so that I can try it, if you need it.

**Comment by DarthMaul113** [comment]
Yeah no problem, i’m using ASP for my app and i changed web.config settings so that the cultural region it’s set to es-Es instead of en-Us, so for example I’m using float values and in typical us format they’d be 1,234.00 but in Spanish formatting, that is very similar to eu format, it’s 1.234,00. The only thing that changes it’s the use of the comma as the decimal separator and dots for the numbers. I hope it’s not a tedious change, let me know if you need more clarification or anything else c:

**Comment by scintilla0** [comment]
It's done, you can check it out. I don't know about ASP, but I think every html should have a [lang] attribute. Please refer to the demo for details, and let me know if that doesn't match your requirement or any bug appears ;3
